name: Scheduled Publish Job

on:
  schedule:
    - cron: "*/5 * * * *" # Every 5 minutes (in UTC)
  workflow_dispatch: # Allows manual trigger from GitHub UI

jobs:
  ping-api:
    runs-on: ubuntu-latest

    steps:
      - name: Make request to publish scheduled posts
        run: |
          curl -X GET "https://prompt-sharing-application.vercel.app/api/schedule/publish"
